### ISSUE TITLE
Feedback from user testter

### ISSUE THREAD

**Issue by MJWainwright** [epistemonikos/isoq#25] opened 2020-10-07 13:57 UTC
My references won't load sometimes. Overall it has been useful
I’ve been uploading the various stuff for the ‘My data’ section and a few issues have emerged (I’ve taken screenshots if these would help):

1. One of the references uploaded from my endnote included a book chapter. This reference was imported very strangely (used the editor as the author name, amongst other issues). I changed the reference in endnote by removing the editor name and name of the book, which enabled the author of the book chapter to be listed in the reference list. Hope this makes sense! Point is, I think there’s an issue with importing book chapters as a reference.

2. When an apostrophe (or single quotation mark) and sometimes double quotation marks are used in my tables (both the characteristics of studies and methodological limitations tables) it displays it as follows: �Dutch bible belt�. It then also puts the red exclamation mark for those tables under the CERQual assessment worksheet. In fact, it doesn't seem to like many symbols in the tables, where it then displays a �

3. Even after removing all the unhappy symbols, the tables still a display red exclamation mark and I just cannot seem to see why!

**Comment by damian-garrido** [comment] 2021-01-07 18:55
@MJWainwright its possible to ask for this kind of references.
i cant reproduce the issue

**Comment by MJWainwright** [comment] 2021-01-08 13:46
Ok, when I have a little more time I will create an .RIS file that also has books and book chapter and will try.

**Comment by MJWainwright** [comment] 2021-01-15 12:41
Here's an .RIS file with three refs, one article, one book, and one book chapter. Let me know how it goes
[Endnote with books and chapters.txt](https://github.com/epistemonikos/isoq/files/5820514/Endnote.with.books.and.chapters.txt)

**Comment by damian-garrido** [comment] 2021-01-15 16:06
i create a new issues for this one, so, im gonna close this.

**Closed by damian-garrido** 2021-01-15 16:06 UTC
Labels: revision
